/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author user
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cudDataRoom = new javax.swing.JMenuItem();
        cudDataItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cudDataBooking = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jMenu1.setText("Room");

        cudDataRoom.setText("CUD Data");
        cudDataRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cudDataRoomActionPerformed(evt);
            }
        });
        jMenu1.add(cudDataRoom);

        cudDataItem.setText("CUD Item");
        cudDataItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cudDataItemActionPerformed(evt);
            }
        });
        jMenu1.add(cudDataItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Booking");

        cudDataBooking.setText("CUD Data");
        cudDataBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cudDataBookingActionPerformed(evt);
            }
        });
        jMenu2.add(cudDataBooking);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cudDataRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cudDataRoomActionPerformed
        // TODO add your handling code here:
        jPanel.removeAll();
        jPanel.repaint();
        jPanel.revalidate();

        RoomForm room = new RoomForm();
        jPanel.add(room);
        room.setVisible(true);    
    }//GEN-LAST:event_cudDataRoomActionPerformed

    private void cudDataBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cudDataBookingActionPerformed
        // TODO add your handling code here:
        jPanel.removeAll();
        jPanel.repaint();
        jPanel.revalidate();

        BookingForm booking = new BookingForm();
        jPanel.add(booking);
        booking.setVisible(true);
    }//GEN-LAST:event_cudDataBookingActionPerformed

    private void cudDataItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cudDataItemActionPerformed
        // TODO add your handling code here:
        jPanel.removeAll();
        jPanel.repaint();
        jPanel.revalidate();

        RoomItemForm roomItem = new RoomItemForm();
        jPanel.add(roomItem);
        roomItem.setVisible(true);
    }//GEN-LAST:event_cudDataItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cudDataBooking;
    private javax.swing.JMenuItem cudDataItem;
    private javax.swing.JMenuItem cudDataRoom;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
