/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import database.DBConnection;
import service.RoomItemService;
import models.RoomItem;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Room;
/**
 *
 * @author user
 */
public class RoomItemForm extends javax.swing.JInternalFrame {
    // Service Layer
    private final RoomItemService itemService;
    
    // UI State
    private DefaultTableModel tableModel;
    private RoomItem selectedItem;
    
    // Map to track Room objects by name
    private Map<String, Room> roomMap = new HashMap<>();
    
    public RoomItemForm() {
        // Initialize database connection
        DBConnection db = new DBConnection();
        Connection con = db.connect();
        
        // Initialize service
        this.itemService = new RoomItemService(con);
        
        // Initialize UI
        initComponents();
        loadRoomsToComboBox();
        refreshTable();
        clearInputs();
    }
    
    // Helper Methods
    
    private void loadRoomsToComboBox() {
        try {
            roomMap.clear();
            
            List<Room> rooms = itemService.getAllRooms();
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            
            for (Room room : rooms) {
                model.addElement(room.getName());
                roomMap.put(room.getName(), room);
            }
            
            roomSelect.setModel(model);
            roomSelect.setSelectedIndex(-1);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Failed to load rooms:\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private RoomItem buildItemFromForm() {
        RoomItem item = new RoomItem();
        item.setName(nameInput.getText().trim());
        item.setQuantity((Integer) quantityInput.getValue());
        
        // Get room ID from selected room name
        String selectedRoomName = (String) roomSelect.getSelectedItem();
        if (selectedRoomName != null) {
            Room selectedRoom = roomMap.get(selectedRoomName);
            if (selectedRoom != null) {
                item.setRoomId(selectedRoom.getId());
                item.setRoomName(selectedRoom.getName());
            }
        }
        
        return item;
    }
    
    private void populateFormWithItem(RoomItem item) {
        nameInput.setText(item.getName());
        quantityInput.setValue(item.getQuantity());
        
        if (item.getRoomName() != null) {
            roomSelect.setSelectedItem(item.getRoomName());
        }
    }
    
    private void refreshTable() {
        tableModel = new DefaultTableModel(
            null,
            new Object[] { "ID", "Name", "Quantity", "Room" }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        itemTable.setModel(tableModel);
        
        try {
            List<RoomItem> items = itemService.getAllItems();
            for (RoomItem item : items) {
                tableModel.addRow(new Object[] {
                    item.getId(),
                    item.getName(),
                    item.getQuantity(),
                    item.getRoomName()
                });
            }
            
            // Hide ID column
            itemTable.getColumnModel().getColumn(0).setMinWidth(0);
            itemTable.getColumnModel().getColumn(0).setMaxWidth(0);
            itemTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Failed to load items:\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void clearInputs() {
        nameInput.setText("");
        quantityInput.setValue(0);
        roomSelect.setSelectedIndex(-1);
        selectedItem = null;
        itemTable.clearSelection();
        editButton.setEnabled(false);
        deleteButton.setEnabled(false);
        createButton.setText("Tambah");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nameInput = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        roomSelect = new javax.swing.JComboBox<>();
        quantityInput = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        quantityLabel.setText("Quantity");

        roomLabel.setText("Room");

        createButton.setText("Tambah");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Hapus");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Batal");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        roomSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roomSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomSelectActionPerformed(evt);
            }
        });

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(itemTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomLabel)
                            .addComponent(quantityLabel)
                            .addComponent(nameLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createButton)
                                .addGap(18, 18, 18)
                                .addComponent(editButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(quantityInput, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(roomSelect, javax.swing.GroupLayout.Alignment.LEADING, 0, 144, Short.MAX_VALUE)
                                .addComponent(nameInput, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(quantityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(roomLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(deleteButton)
                    .addComponent(editButton)
                    .addComponent(cancelButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        RoomItem item = buildItemFromForm();
        
        try {
            itemService.createRoomItem(item);
            JOptionPane.showMessageDialog(this,
                "Item created successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
            clearInputs();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Failed to create item:\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void roomSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomSelectActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        clearInputs();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (selectedItem == null) {
            JOptionPane.showMessageDialog(this,
                "Please select an item from the table first.",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete '" + selectedItem.getName() + "'?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                itemService.deleteRoomItem(selectedItem.getId());
                JOptionPane.showMessageDialog(this,
                    "Item deleted successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
                clearInputs();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Failed to delete item:\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if (selectedItem == null) {
            JOptionPane.showMessageDialog(this,
                "Please select an item from the table first.",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Update selected item with form data
        selectedItem.setName(nameInput.getText().trim());
        selectedItem.setQuantity((Integer) quantityInput.getValue());
        
        String selectedRoomName = (String) roomSelect.getSelectedItem();
        if (selectedRoomName != null) {
            Room selectedRoom = roomMap.get(selectedRoomName);
            if (selectedRoom != null) {
                selectedItem.setRoomId(selectedRoom.getId());
            }
        }
        
        try {
            itemService.updateRoomItem(selectedItem);
            JOptionPane.showMessageDialog(this,
                "Item updated successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
            clearInputs();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Validation Error",
                JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Failed to update item:\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = itemTable.getSelectedRow();
        if (selectedRow >= 0) {
            Integer itemId = (Integer) tableModel.getValueAt(selectedRow, 0);
            
            try {
                selectedItem = itemService.getItemById(itemId);
                if (selectedItem != null) {
                    populateFormWithItem(selectedItem);
                    editButton.setEnabled(true);
                    deleteButton.setEnabled(true);
                    createButton.setText("Simpan Baru");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Failed to load item details:\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_itemTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTable itemTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JSpinner quantityInput;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JComboBox<String> roomSelect;
    // End of variables declaration//GEN-END:variables
}
